import { StyleSheet } from '@react-pdf/renderer';

export const stylesInternal = StyleSheet.create({
  page: {
    padding: 18,
    fontFamily: 'Helvetica',
    fontSize: 8,
    color: '#0f172a',
    backgroundColor: '#ffffff',
  },
  watermark: {
    position: 'absolute',
    top: 110,
    left: 320,
    width: 260,
    height: 260,
    opacity: 0.03,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 3,
    borderBottomColor: '#0f172a',
    paddingBottom: 10,
    marginBottom: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  headerLogo: {
    width: 56,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  headerLogoImg: {
    width: 56,
    height: 56,
  },
  headerTitle: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
  },
  headerSubtitle: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#94a3b8',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  headerMetaRow: {
    flexDirection: 'row',
    marginTop: 4,
  },
  headerMetaText: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#64748b',
    textTransform: 'uppercase',
    marginRight: 8,
  },
  headerBadge: {
    backgroundColor: '#0f172a',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: 'flex-end',
  },
  headerBadgeLabel: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    color: '#34d399',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 2,
  },
  headerBadgeTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-BoldOblique',
    color: '#ffffff',
    textTransform: 'uppercase',
  },
  headerBadgeNote: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    color: '#94a3b8',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  kpiRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  kpiItem: {
    flex: 1,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 14,
    padding: 10,
    marginRight: 8,
  },
  kpiItemDark: {
    backgroundColor: '#0f172a',
    borderColor: '#10b981',
  },
  kpiItemLast: {
    marginRight: 0,
  },
  kpiLabel: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    color: '#94a3b8',
    textTransform: 'uppercase',
  },
  kpiValue: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
    marginTop: 3,
  },
  kpiValueLight: {
    color: '#ffffff',
  },
  kpiHint: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    color: '#94a3b8',
    textTransform: 'uppercase',
    marginTop: 4,
  },
  progressTrack: {
    height: 4,
    backgroundColor: '#e2e8f0',
    borderRadius: 4,
    marginTop: 6,
  },
  progressFill: {
    height: 4,
    borderRadius: 4,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#0f172a',
    paddingVertical: 6,
    paddingHorizontal: 6,
  },
  tableHeaderCell: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    color: '#ffffff',
    textTransform: 'uppercase',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  tableRowOdd: {
    backgroundColor: '#f8fafc',
  },
  tableCell: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
  },
  tableCellSmall: {
    fontSize: 6,
    fontFamily: 'Helvetica',
    color: '#94a3b8',
    marginTop: 2,
  },
  tableTotalRow: {
    flexDirection: 'row',
    paddingVertical: 6,
    paddingHorizontal: 6,
    backgroundColor: '#e2e8f0',
  },
  panelRow: {
    flexDirection: 'row',
    marginTop: 8,
    marginBottom: 8,
  },
  panel: {
    flex: 1,
    marginRight: 12,
  },
  panelLast: {
    marginRight: 0,
  },
  panelTitle: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    borderBottomWidth: 2,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 4,
    marginBottom: 6,
  },
  panelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  panelCard: {
    width: '48%',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 6,
    marginBottom: 6,
    marginRight: 6,
  },
  panelLabel: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    color: '#94a3b8',
    textTransform: 'uppercase',
  },
  panelValue: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
    marginTop: 2,
  },
  panelValueWarn: {
    color: '#be123c',
  },
  panelListItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 6,
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    marginBottom: 4,
  },
  notesSection: {
    marginTop: 8,
    paddingTop: 6,
    borderTopWidth: 2,
    borderTopColor: '#0f172a',
  },
  notesTitle: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  notesText: {
    fontSize: 6,
    fontFamily: 'Helvetica',
    color: '#64748b',
    lineHeight: 1.4,
  },
  approvalBox: {
    alignItems: 'center',
  },
  approvalLine: {
    height: 30,
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
    width: '100%',
    marginBottom: 4,
  },
  approvalName: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
  },
  approvalRole: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    color: '#94a3b8',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  footer: {
    marginTop: 6,
    backgroundColor: '#0f172a',
    borderRadius: 12,
    padding: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerText: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    color: '#94a3b8',
    textTransform: 'uppercase',
  },
  footerAccent: {
    color: '#34d399',
  },
});
