import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  page: {
    padding: 25,
    fontFamily: 'Helvetica',
    fontSize: 8,
    color: '#0f172a',
    backgroundColor: '#ffffff',
  },
  watermark: {
    position: 'absolute',
    top: 140,
    left: 104,
    opacity: 0.05,
    width: 387,
    height: 387,
    zIndex: 0,
  },
  // CABEÇALHO
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottom: 2,
    borderBottomColor: '#0f172a',
    paddingBottom: 15,
    marginBottom: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    gap: 15,
    alignItems: 'center',
  },
  logo: {
    width: 55,
    height: 55,
  },
  companyInfo: {
    gap: 2,
  },
  companyName: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#0f172a',
  },
  companySubtitle: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 2,
  },
  companyDetails: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#475569',
    textTransform: 'uppercase',
    marginTop: 4,
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  reportTitle: {
    fontSize: 15,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
    textTransform: 'uppercase',
  },
  reportBadge: {
    backgroundColor: '#0f172a',
    color: '#ffffff',
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginTop: 6,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  reportMeta: {
    fontSize: 6,
    color: '#64748b',
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    marginTop: 4,
  },
  // METADADOS
  metadataGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 15,
  },
  metadataCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 8,
    backgroundColor: '#f8fafc',
  },
  metadataLabel: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#64748b',
    marginBottom: 2,
  },
  metadataValue: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
  },
  // KPI CARDS
  kpiGrid: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 18,
  },
  kpiCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 8,
    padding: 8,
    alignItems: 'center',
  },
  kpiCardPrimary: {
    backgroundColor: '#0f172a',
    borderColor: '#0f172a',
  },
  kpiLabel: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    marginBottom: 3,
  },
  kpiValue: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
  },
  // SECTIONS
  section: {
    marginBottom: 15,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#0f172a',
    borderBottom: 2,
    borderBottomColor: '#0f172a',
    paddingBottom: 3,
  },
  sectionSubtitle: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    color: '#64748b',
    textTransform: 'uppercase',
  },
  // CONTEXT GRID
  contextGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
  },
  contextCard: {
    flex: 1,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 10,
  },
  contextTitle: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#0f172a',
    borderBottom: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 5,
    marginBottom: 6,
  },
  contextRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 6,
  },
  contextItem: {
    flex: 1,
  },
  contextLabel: {
    fontSize: 6,
    color: '#64748b',
    marginBottom: 1,
  },
  contextValue: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
  },
  contextBalance: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginBottom: 4,
  },
  contextBalanceBank: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#475569',
    flex: 1,
  },
  contextBalanceValue: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
  },
  // BANK TABLE
  table: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 15,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f1f5f9',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
  },
  tableHeaderCell: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#475569',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    backgroundColor: 'rgba(255,255,255,0.8)',
  },
  tableCell: {
    fontSize: 7,
  },
  tableCellBold: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
  },
  // CONSOLIDATED MIRROR
  mirrorGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
  },
  mirrorColumn: {
    flex: 1,
  },
  mirrorTitle: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    paddingBottom: 3,
    marginBottom: 6,
    borderBottom: 2,
  },
  mirrorItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
    paddingHorizontal: 6,
    marginBottom: 4,
    borderWidth: 1,
    borderRadius: 4,
  },
  mirrorLabel: {
    fontSize: 6.5,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    flex: 1,
  },
  mirrorValue: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
  },
  mirrorTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginTop: 4,
    borderWidth: 1,
    borderColor: '#0f172a',
    borderRadius: 4,
  },
  mirrorTotalLabel: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#000000',
  },
  mirrorTotalValue: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#000000',
  },
  // FINAL BALANCE
  finalBox: {
    backgroundColor: '#0f172a',
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 12,
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 20,
  },
  finalLeft: {
    gap: 2,
  },
  finalTitle: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#94a3b8',
    letterSpacing: 1,
  },
  finalSubtitle: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#cbd5e1',
  },
  finalRight: {
    alignItems: 'flex-end',
  },
  finalLabel: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#cbd5e1',
    marginBottom: 2,
  },
  finalValue: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
  },
  // FOOTER
  footer: {
    position: 'absolute',
    bottom: 15,
    left: 25,
    right: 25,
    borderTop: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 6,
    fontFamily: 'Helvetica-Bold',
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  // GRÁFICOS
  chartSection: {
    marginBottom: 20,
  },
  chartTitle: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#0f172a',
    marginBottom: 15,
    borderBottom: 2,
    borderBottomColor: '#0f172a',
    paddingBottom: 5,
  },
  chartGrid: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 20,
  },
  chartBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 15,
    backgroundColor: '#f8fafc',
  },
  chartBoxTitle: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#475569',
    marginBottom: 12,
    textAlign: 'center',
  },
  chartLegend: {
    marginTop: 15,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  legendColor: {
    width: 12,
    height: 12,
    marginRight: 8,
    borderRadius: 2,
  },
  legendLabel: {
    fontSize: 7,
    color: '#475569',
    flex: 1,
  },
  legendValue: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
  },
  barChart: {
    marginTop: 10,
  },
  barItem: {
    marginBottom: 8,
  },
  barLabel: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#475569',
    marginBottom: 3,
  },
  barContainer: {
    height: 20,
    backgroundColor: '#e2e8f0',
    borderRadius: 4,
    overflow: 'hidden',
    position: 'relative',
  },
  barFill: {
    height: '100%',
    borderRadius: 4,
  },
  barValue: {
    position: 'absolute',
    right: 5,
    top: 3,
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#ffffff',
  },
});
