-- ============================================================================
-- Fix: Trigger automático ao descarregar carga (unload)
-- ============================================================================
-- Quando ops_loadings.unload_weight_kg é preenchido (e tem sales_order_id):
--   1) Insere/atualiza ops_sales_order_unloads
--   2) Cria financial_entry receivable (se não existir)
-- Quando ops_loadings.status muda para 'completed':
--   Mesma lógica, mas usa o peso de descarregamento já existente.
--
-- Arquitetura SQL-first: frontend NÃO faz cálculos, apenas exibe.
-- ============================================================================

-- ═══════════════════════════════════════════════════════════════════════════
-- 1) TRIGGER: auto-sync unload + receivable ao atualizar ops_loadings
-- ═══════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.trg_loading_unload_sync()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_unload_weight  NUMERIC;
  v_sales_price    NUMERIC;
  v_delivered_value NUMERIC;
  v_existing_entry UUID;
  v_sales_order_uuid UUID;
BEGIN
  -- Só processa se tem sales_order_id e peso de descarregamento
  v_unload_weight := COALESCE(NEW.unload_weight_kg, 0);
  
  IF NEW.sales_order_id IS NULL OR v_unload_weight <= 0 THEN
    RETURN NEW;
  END IF;

  -- Resolve o UUID real do pedido de venda (pode ser legacy_id)
  SELECT id INTO v_sales_order_uuid
  FROM public.ops_sales_orders
  WHERE (id = NEW.sales_order_id OR legacy_id = NEW.sales_order_id)
    AND company_id = NEW.company_id
  LIMIT 1;

  IF v_sales_order_uuid IS NULL THEN
    RETURN NEW;
  END IF;

  -- Calcula preço de venda e valor entregue
  v_sales_price := COALESCE(
    (NEW.metadata->>'salesPrice')::numeric,
    (SELECT (so.metadata->>'unitPrice')::numeric FROM ops_sales_orders so WHERE so.id = v_sales_order_uuid),
    0
  );
  v_delivered_value := (v_unload_weight / 60.0) * v_sales_price;

  -- ═══════ 1) UPSERT ops_sales_order_unloads ═══════
  INSERT INTO public.ops_sales_order_unloads (
    id, company_id, sales_order_id, loading_id, legacy_id,
    unload_date, unload_weight_kg, metadata, created_at, updated_at
  ) VALUES (
    gen_random_uuid(),
    NEW.company_id,
    v_sales_order_uuid,
    NEW.id,
    NEW.legacy_id,
    COALESCE(NEW.loading_date, CURRENT_DATE),
    v_unload_weight,
    jsonb_build_object(
      'salesPrice', v_sales_price,
      'deliveredValue', v_delivered_value,
      'autoGenerated', true
    ),
    now(),
    now()
  )
  ON CONFLICT (loading_id) WHERE loading_id IS NOT NULL
  DO UPDATE SET
    unload_weight_kg = EXCLUDED.unload_weight_kg,
    unload_date = EXCLUDED.unload_date,
    metadata = EXCLUDED.metadata,
    updated_at = now();

  -- ═══════ 2) UPSERT financial_entry receivable ═══════
  -- Verifica se já existe receivable para esta carga
  SELECT id INTO v_existing_entry
  FROM public.financial_entries
  WHERE company_id = NEW.company_id
    AND type = 'receivable'
    AND origin_type = 'sales_order'
    AND origin_id = COALESCE(NEW.legacy_id, NEW.id)
  LIMIT 1;

  IF v_existing_entry IS NULL THEN
    -- Tenta com o sales_order_id como origin_id
    SELECT id INTO v_existing_entry
    FROM public.financial_entries
    WHERE company_id = NEW.company_id
      AND type = 'receivable'
      AND origin_type = 'sales_order'
      AND origin_id = v_sales_order_uuid
    LIMIT 1;
  END IF;

  IF v_existing_entry IS NOT NULL THEN
    -- Atualiza o valor do receivable existente
    UPDATE public.financial_entries
    SET total_amount = v_delivered_value,
        status = CASE
          WHEN paid_amount >= v_delivered_value THEN 'paid'
          WHEN paid_amount > 0 THEN 'partially_paid'
          ELSE 'open'
        END,
        updated_at = now()
    WHERE id = v_existing_entry;
  ELSE
    -- Cria receivable novo
    INSERT INTO public.financial_entries (
      id, company_id, type, origin_type, origin_id,
      partner_id, total_amount, paid_amount,
      status, created_date, due_date, created_at, updated_at
    ) VALUES (
      gen_random_uuid(),
      NEW.company_id,
      'receivable',
      'sales_order',
      v_sales_order_uuid,
      (SELECT customer_id FROM ops_sales_orders WHERE id = v_sales_order_uuid),
      v_delivered_value,
      0,
      'open',
      CURRENT_DATE,
      CURRENT_DATE + INTERVAL '30 days',
      now(),
      now()
    );
  END IF;

  RETURN NEW;
END;
$$;

-- Cria o trigger (DROP + CREATE para idempotência)
DROP TRIGGER IF EXISTS trg_loading_unload_sync ON public.ops_loadings;
CREATE TRIGGER trg_loading_unload_sync
  AFTER INSERT OR UPDATE OF unload_weight_kg, status
  ON public.ops_loadings
  FOR EACH ROW
  WHEN (
    COALESCE(NEW.unload_weight_kg, 0) > 0
    AND NEW.sales_order_id IS NOT NULL
  )
  EXECUTE FUNCTION public.trg_loading_unload_sync();

-- ═══════════════════════════════════════════════════════════════════════════
-- 2) Criar unique index em ops_sales_order_unloads para suportar ON CONFLICT
-- ═══════════════════════════════════════════════════════════════════════════
CREATE UNIQUE INDEX IF NOT EXISTS uq_sales_order_unloads_loading
  ON public.ops_sales_order_unloads (loading_id)
  WHERE loading_id IS NOT NULL;

-- ═══════════════════════════════════════════════════════════════════════════
-- 3) FIX VIEW: usar ops_loadings diretamente (não depender apenas de unloads)
-- A view agora calcula delivered a partir do loading quando unload_weight > 0,
-- independente de existir registro em ops_sales_order_unloads.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE VIEW public.vw_sales_orders_enriched AS
SELECT
  so.id,
  so.company_id,
  so.legacy_id,
  so.number,
  so.order_date,
  so.status,
  so.customer_id,
  so.customer_name,
  so.total_value,
  so.received_value,
  so.metadata,
  so.raw_payload,
  so.created_at,
  so.updated_at,

  -- ═══════ Dados de entrega (cargas com unload_weight_kg > 0) ═══════
  COALESCE(delivered.delivered_qty_sc, 0)         AS delivered_qty_sc,
  COALESCE(delivered.delivered_value, 0)          AS delivered_value,
  COALESCE(delivered.load_count, 0)::int          AS load_count,

  -- ═══════ Mercadoria em trânsito (sem descarregamento) ═══════
  COALESCE(transit.transit_count, 0)::int         AS transit_count,
  COALESCE(transit.transit_value, 0)              AS transit_value

FROM public.ops_sales_orders so

-- Cargas entregues: usa diretamente ops_loadings.unload_weight_kg
LEFT JOIN LATERAL (
  SELECT
    COUNT(*)::int AS load_count,
    COALESCE(SUM(ol.unload_weight_kg / 60.0), 0) AS delivered_qty_sc,
    COALESCE(SUM(
      (ol.unload_weight_kg / 60.0) *
      COALESCE(
        (ol.metadata->>'salesPrice')::numeric,
        (so.metadata->>'unitPrice')::numeric,
        0
      )
    ), 0) AS delivered_value
  FROM public.ops_loadings ol
  WHERE (ol.sales_order_id = so.id OR ol.sales_order_id = so.legacy_id)
    AND COALESCE(ol.unload_weight_kg, 0) > 0
    AND ol.status NOT IN ('canceled')
) delivered ON true

-- Cargas em trânsito (sem descarregamento)
LEFT JOIN LATERAL (
  SELECT
    COUNT(*)::int AS transit_count,
    COALESCE(SUM(
      (ol.weight_kg / 60.0) *
      COALESCE(
        (ol.metadata->>'salesPrice')::numeric,
        (so.metadata->>'unitPrice')::numeric,
        0
      )
    ), 0) AS transit_value
  FROM public.ops_loadings ol
  WHERE (ol.sales_order_id = so.id OR ol.sales_order_id = so.legacy_id)
    AND COALESCE(ol.unload_weight_kg, 0) = 0
    AND ol.status IN ('loaded', 'in_transit', 'redirected', 'waiting_unload')
) transit ON true;

GRANT SELECT ON public.vw_sales_orders_enriched TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- 4) BACKFILL: Gerar unloads + receivables para cargas já descarregadas
-- ═══════════════════════════════════════════════════════════════════════════
-- Isso vai disparar o trigger para cargas existentes com unload_weight_kg > 0
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT id, unload_weight_kg
    FROM public.ops_loadings
    WHERE unload_weight_kg > 0
      AND sales_order_id IS NOT NULL
  LOOP
    -- Touch para disparar o trigger: seta o mesmo valor
    UPDATE public.ops_loadings
    SET unload_weight_kg = r.unload_weight_kg,
        updated_at = now()
    WHERE id = r.id;
  END LOOP;
END;
$$;
